[package]
name = "blockchain"
version = "0.1.0"
authors = ["Hasan Genc <hasangencx@hotmail.com>"]
edition = "2018"

[dependencies]
crypto-hash = "0.3.3"
chrono = { version = "0.4", features = ["serde"] }
serde = "*"
serde_json = "*"
serde_derive = "*"
actix-web = "1.0.0"
